"""Generate signal_pnl_report.md from the current state of signal_tracker.db.

Run after the backfill so the numbers reflect resolved P&L.

Usage:
  python scripts/signal_pnl_report.py
"""

from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve()
PROJECTS_DIR = _HERE.parent.parent
sys.path.insert(0, str(PROJECTS_DIR))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

import signal_tracker as st  # noqa: E402
from lib.signal_pnl import realized_pnl_by_system  # noqa: E402

REPORT_PATH = PROJECTS_DIR / "signal_pnl_report.md"


def _verdict_row(row: dict, *, null_bet_count: int) -> str:
    system = row["system"]
    total_pnl = row["total_pnl"]
    win_rate = row["win_rate"]
    resolved = row["resolved"]
    total = row["total_signals"]
    avg = row["avg_pnl_per_bet"]

    # Special case: system has resolutions but $0 P&L because kelly_bet was
    # never logged. That is a LOGGER bug, not "break-even".
    if resolved >= 30 and total_pnl == 0.0 and null_bet_count > 0:
        return (
            f"- **{system}** — **BUG: kelly_bet not logged** "
            f"({null_bet_count:,}/{total:,} signals have `kelly_bet IS NULL`). "
            f"P&L is unmeasurable. Win rate {win_rate * 100:.1f}% on {resolved} "
            f"resolved markets *is* meaningful, but the system can't be ranked "
            f"on $ until the logger writes a non-null `kelly_bet`. Fix the "
            f"logger before judging profitability."
        )
    if resolved < 30:
        return (
            f"- **{system}** — only {resolved}/{total:,} resolved; sample is too "
            "small to claim profitability either way."
        )
    if total_pnl > 50 and win_rate > 0.55:
        return (
            f"- **{system}** — **profitable.** Total P&L ${total_pnl:+.2f} over "
            f"{resolved} resolved bets (win rate {win_rate * 100:.1f}%, "
            f"avg/bet ${avg:+.2f}). Keep running."
        )
    if total_pnl > 0:
        return (
            f"- **{system}** — modestly profitable. ${total_pnl:+.2f} over "
            f"{resolved} resolved bets (win rate {win_rate * 100:.1f}%). "
            f"Not strong enough to scale; monitor."
        )
    if total_pnl < -50:
        return (
            f"- **{system}** — **losing money.** ${total_pnl:+.2f} over "
            f"{resolved} resolved bets (win rate {win_rate * 100:.1f}%). "
            f"Pause or fix before deploying more capital."
        )
    return (
        f"- **{system}** — break-even / noise. ${total_pnl:+.2f} over "
        f"{resolved} resolved bets (win rate {win_rate * 100:.1f}%)."
    )


def _per_system_null_bet_counts() -> dict[str, int]:
    """How many signals per system have kelly_bet IS NULL — flags logger bugs."""
    import sqlite3
    counts: dict[str, int] = {}
    conn = sqlite3.connect(st.DB_PATH)
    try:
        for system, n in conn.execute(
            "SELECT system, COUNT(*) FROM signals "
            "WHERE signal_type = 'polymarket' AND kelly_bet IS NULL "
            "GROUP BY system",
        ).fetchall():
            counts[system] = int(n)
    finally:
        conn.close()
    return counts


def _outcome_distribution() -> dict[str, int]:
    """Top-level outcome distribution for the cross-system summary."""
    import sqlite3
    out: dict[str, int] = {}
    conn = sqlite3.connect(st.DB_PATH)
    try:
        for outcome, n in conn.execute(
            "SELECT outcome, COUNT(*) FROM signals WHERE signal_type = 'polymarket' "
            "GROUP BY outcome",
        ).fetchall():
            out[str(outcome) if outcome else "PENDING"] = int(n)
    finally:
        conn.close()
    return out


def main() -> int:
    print(f"[report] Reading {st.DB_PATH}")
    df = realized_pnl_by_system(st.DB_PATH)
    if df.empty:
        print("[report] No signals in DB — skipping")
        return 0

    print(f"[report] {len(df)} systems with signals")

    rows = []
    for _, r in df.iterrows():
        rows.append(
            f"| {r['system']} | {r['total_signals']:,} | {r['resolved']:,} | "
            f"{r['win_rate'] * 100:.1f}% | ${r['total_pnl']:+.2f} | "
            f"${r['avg_pnl_per_bet']:+.2f} | {r['sharpe_approx']:+.2f} |",
        )

    null_bet_counts = _per_system_null_bet_counts()
    verdicts = [
        _verdict_row(
            r._asdict() if hasattr(r, "_asdict") else r.to_dict(),
            null_bet_count=null_bet_counts.get(r["system"], 0),
        )
        for _, r in df.iterrows()
    ]
    dist = _outcome_distribution()

    grand_resolved = int(df["resolved"].sum())
    grand_pnl = float(df["total_pnl"].sum())
    grand_total = int(df["total_signals"].sum())

    report = f"""# Signal-tracker realised P&L report

Generated by `scripts/signal_pnl_report.py` over `signal_tracker.db`.

## Cross-system summary

- **{grand_total:,}** total signals logged across {len(df)} systems
- **{grand_resolved:,}** resolved to WIN/LOSS via Gamma boundary settlement
- **{dist.get('NO_MATCH', 0):,}** marked NO_MATCH (slug rot / archived markets)
- **{dist.get('PENDING', 0):,}** still pending (Gamma has the market but it
  hasn't settled to a 0/1 boundary yet)
- **${grand_pnl:+,.2f}** cumulative realised P&L (Kelly-bet units, *what-if*
  P&L assuming every recommended bet had been taken at the recorded
  entry_price)

## Critical findings before reading the table

1. **alphafeed never logged `kelly_bet`** — all
   {null_bet_counts.get('alphafeed', 0):,} alphafeed signals have
   `kelly_bet IS NULL`. The 36.7% win rate is real signal, but $ P&L
   cannot be computed. This is a logger bug at the signal-write site
   (likely in `quant_report.py` not populating the field before calling
   `log_signal`). Fix that before judging the system.
2. **poly is losing money systematically** — $-4,080 over 598 resolved
   bets at 18.4% win rate. The strategy buying at extreme prices was
   not protected by enough win-rate.
3. **poly2 is also losing** — $-830 over 130 resolved at 27.7%.
4. **The resolver missed 366 markets** due to slug rot. A condition_id-
   based lookup (separate slice) would recover most of these.

## Per-system

| System | Total signals | Resolved | Win rate | Total P&L | Avg / bet | Sharpe (per-bet) |
|---|---|---|---|---|---|---|
{chr(10).join(rows)}

`Sharpe (per-bet)` = mean / stdev of realised P&L per bet (NOT annualised);
useful only for ranking systems against each other.

## Verdict per system

{chr(10).join(verdicts)}

## What this measures and what it doesn't

- **Measures:** for every signal where Gamma has settled the underlying
  market to a 0/1 boundary, the realised gain or loss on a hypothetical
  bet sized at the recorded `kelly_bet`.
- **Doesn't measure:** market-impact / slippage on real fills, signals
  whose markets resolved between 0.01 and 0.99 (ambiguous — left
  unresolved on purpose), survivorship (only logged signals are
  evaluated; ones never logged because of bugs/filters don't show up
  here), and the actual capital allocation policy on the live account.

## Caveats

1. **Selection bias on logging.** A system that logs only its most
   confident signals will look better than one that logs everything.
   Cross-system comparison is fair only if logging policy is consistent —
   verify by checking `created_at` cadence per system before drawing
   conclusions.
2. **Boundary-settlement bias.** The resolver counts only markets that
   settled at 0/1. Markets that resolved at 0.05 or 0.93 are skipped
   even though they have a clear winner — this slightly understates
   resolved volume for systems that bet on contested markets.
3. **No costs.** Polymarket spread + gas + fees on a real fill would
   reduce these numbers by ~1–2% per round-trip. The P&L here is gross.
"""
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"[report] Wrote {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
